[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/services/*"
  to = "/services/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404 